/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.FlowLayout;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Mohammad Mansour
 */
public class mainpagegui extends javax.swing.JFrame {
    class cart1{
        String c1;
        double c1q;
        double c1p;
        String c2;
        double c2q;
        double c2p;
        String e1;
        double e1q;
        double e1p;
        String e2;
        double e2q;
        double e2p;
        public cart1(){
            this.c1="";
            this.c2="";
            this.c1q=0;
            this.c2q=0;
            this.c1p=0;
            this.c2p=0;
            this.e1="";
            this.e2="";
            this.e1q=0;
            this.e2q=0;
            this.e1p=0;
            this.e2p=0;
        }
    }
    cart1 cart_s=new cart1();
    static mainpagegui Global;
    Socket socket = null;
    OutputStream out = null;
    PrintWriter p = null;
    BufferedReader in = null;
    int Genderr=2;//to make sure that the user chose a radio button
    public mainpagegui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        login = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        login_submit = new javax.swing.JButton();
        BAck_login = new javax.swing.JButton();
        register = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        u_Name = new javax.swing.JTextField();
        fn_sign = new javax.swing.JTextField();
        ln_sign = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        pass_sign = new javax.swing.JTextField();
        cofirm_sign = new javax.swing.JTextField();
        address_sign = new javax.swing.JTextField();
        sign_btn = new javax.swing.JButton();
        Back_signup = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        shopping = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        shopping_login_signup = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        item1 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        item1_count = new javax.swing.JSpinner();
        item2_count = new javax.swing.JSpinner();
        item1_p = new javax.swing.JLabel();
        item2_p = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Buy = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        cart_display = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cart_names = new javax.swing.JList<>();
        back_cart = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        total_cart = new javax.swing.JLabel();
        total_price = new javax.swing.JLabel();
        cq_test = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        buypage = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        signbtn = new javax.swing.JButton();
        pcpage = new javax.swing.JButton();

        login.setName("login"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("username:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("password:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("EECE 350 | Spring@2020");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(22, 22, 22))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        userName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        login_submit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_submit.setText("Login");
        login_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_submitActionPerformed(evt);
            }
        });

        BAck_login.setText("Back");
        BAck_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAck_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAck_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(login_submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BAck_login))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_submit)
                    .addComponent(BAck_login))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        u_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        u_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        fn_sign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fn_sign.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ln_sign.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ln_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ln_signActionPerformed(evt);
            }
        });

        day.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        day.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        month.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        month.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        female.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        female.setText("female");

        male.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        male.setText("male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        pass_sign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pass_sign.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cofirm_sign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cofirm_sign.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        address_sign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        address_sign.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        sign_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sign_btn.setText("Sign Up");
        sign_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_btnActionPerformed(evt);
            }
        });

        Back_signup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back_signup.setText("Back");
        Back_signup.setActionCommand("<=");
        Back_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_signupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address_sign)
                    .addComponent(cofirm_sign)
                    .addComponent(pass_sign)
                    .addComponent(fn_sign)
                    .addComponent(ln_sign)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(female))
                    .addComponent(u_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sign_btn)
                .addGap(26, 26, 26)
                .addComponent(Back_signup)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(u_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(fn_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ln_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(12, 12, 12)
                .addComponent(pass_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cofirm_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(address_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign_btn)
                    .addComponent(Back_signup))
                .addGap(37, 37, 37))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("first name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("last name");

        DOB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setText("date of birth");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("confirm password");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(DOB)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(DOB)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("EECE 350 | Spring@2020");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register.getContentPane());
        register.getContentPane().setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField11.setText("jTextField11");

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        shopping_login_signup.setText("Signup/Login");
        shopping_login_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopping_login_signupActionPerformed(evt);
            }
        });

        cart.setText("cart");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));

        item1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        item1.setText("item1");

        item2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        item2.setText("item2");

        item1_count.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        item2_count.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        item1_p.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        item1_p.setText("p1");

        item2_p.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        item2_p.setText("p2");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("$/unit");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("$/unit");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item2)
                    .addComponent(item1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item1_p, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item2_p, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(33, 33, 33)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(item1_count)
                    .addComponent(item2_count))
                .addGap(82, 82, 82))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1)
                    .addComponent(item1_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1_p)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2_p)
                    .addComponent(jLabel22))
                .addGap(81, 81, 81))
        );

        Buy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Buy.setText("Buy");
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(shopping_login_signup)
                        .addGap(18, 18, 18)
                        .addComponent(cart)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(Buy)
                        .addGap(49, 49, 49))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopping_login_signup)
                    .addComponent(cart))
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Buy)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout shoppingLayout = new javax.swing.GroupLayout(shopping.getContentPane());
        shopping.getContentPane().setLayout(shoppingLayout);
        shoppingLayout.setHorizontalGroup(
            shoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        shoppingLayout.setVerticalGroup(
            shoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shoppingLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("EECE 350 | Spring@2020");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("EECE 350 | Spring@2020");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Thank you for choosing our store!");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        cart_names.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(cart_names);

        back_cart.setText("Back");
        back_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_cartActionPerformed(evt);
            }
        });

        jButton2.setText("Checkout");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Total");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        total_cart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_cart.setText("  .");

        total_price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(back_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total_cart)
                .addGap(87, 87, 87)
                .addComponent(total_price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(127, 127, 127))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(total_cart)
                    .addComponent(total_price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_cart)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout cart_displayLayout = new javax.swing.GroupLayout(cart_display.getContentPane());
        cart_display.getContentPane().setLayout(cart_displayLayout);
        cart_displayLayout.setHorizontalGroup(
            cart_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cart_displayLayout.setVerticalGroup(
            cart_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cart_displayLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cq_test.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Welcome to the 350 Online store");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("EECE 350 | Spring@2020");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(47, 47, 47))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        buypage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buypage.setText("Electronics");
        buypage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buypageActionPerformed(evt);
            }
        });

        loginbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginbtn.setText("login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        signbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signbtn.setText("signup");
        signbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signbtnActionPerformed(evt);
            }
        });

        pcpage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pcpage.setText("Computers");
        pcpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcpageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pcpage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buypage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(signbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn)
                    .addComponent(signbtn))
                .addGap(18, 18, 18)
                .addComponent(pcpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buypage)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
         
        Global.setVisible(false);
        JDialog login_dialog= Global.login;
        login_dialog.pack();
        login_dialog.setLocationRelativeTo(null);
        login_dialog.setVisible(true);
    }                                        

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void ln_signActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void signbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Global.setVisible(false);                                        
        JDialog signup_dialog= Global.register;
        signup_dialog.pack();
        signup_dialog.setLocationRelativeTo(null);
        signup_dialog.setVisible(true);
    }                                       

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {                                    
        
        try {
            item1_count.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
        }
        if((double)item1_count.getValue()>0)
        {
            System.out.println("ITEM1 is added");
            if(cq_test.getText().equals("computers"))
            {
                cart_s.c1=item1.getText();
                cart_s.c1p= Double.parseDouble( item1_p.getText());
                cart_s.c1q+=(double)item1_count.getValue();
            }else if(cq_test.getText().equals("electronics"))
            {
                cart_s.e1=item1.getText();
                cart_s.e1p= Double.parseDouble( item1_p.getText());
                cart_s.e1q+=(double)item1_count.getValue();
            }else{
                System.out.println("ERRORRR cq_test was not set to be used in cart");
            }
        }
        if((double)item2_count.getValue()>0)
        {
            if(cq_test.getText().equals("computers"))
            {
                cart_s.c2=item2.getText();
                cart_s.c2p= Double.parseDouble( item2_p.getText());
                cart_s.c2q+=(double)item2_count.getValue();
            }else if(cq_test.getText().equals("electronics"))
            {
                cart_s.e2=item2.getText();
                cart_s.e2p= Double.parseDouble( item2_p.getText());
                cart_s.e2q+=(double)item2_count.getValue();
            }else{
                System.out.println("ERRORRR cq_test was not set to be used in cart");
            }
        }
        item1.setText("");
        item2.setText("");
        shopping.setVisible(false);
        shopping.pack();
        shopping.setLocationRelativeTo(null);
        Global.setVisible(true);
    }                                   

    private void login_submitActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String Uname = userName.getText();
        String pass = password.getText();
        if (Uname.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the Fields !");
            utils_login();
            password.requestFocusInWindow();
        } //LibraryClient m = new LibraryClient();
        else{
            try {
            socket = new Socket("127.0.0.1",7100);
            out = socket.getOutputStream();
            p = new PrintWriter(out, true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            } catch (IOException ex) {
                Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
            }
            String server_answer = "";
                p.println("loginstore~"+Uname+"~"+pass+"~");//sends the username and pass to the server
            try {
                server_answer=in.readLine();
            } catch (IOException ex) {
                Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(server_answer.equals("successFinish!")){//the user logged in     
                JOptionPane.showMessageDialog(null, "Login Successful!");
                utils_login();
                login.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Username or Password are incorrect.");
                utils_login();
                password.requestFocusInWindow();
                p.println("Q");
            }
        }
    }                                            

    private void buypageActionPerformed(java.awt.event.ActionEvent evt) {                                        
        cq_test.setText("electronics");
        /*Get the list of available and unavailable items.
        1- send message to server as "ShowItems"
        2- server returns a message booleans in the order of items such that
        for item1 and item2 server will returns "1~0" meaning that item1
        is available while 2 is not. Can be fixed to nb of available if needed"
        */
        try {
            socket = new Socket("127.0.0.1",7100);
            out = socket.getOutputStream();
            p = new PrintWriter(out, true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            } catch (IOException ex) {
                Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
            }
            String server_answer = "";
            p.println("ShowItems~electronics~q");
            try {
                server_answer=in.readLine();
            } catch (IOException ex) {
                Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
            }
        String reply_items[] = server_answer.split("~~~");
        String item_list[] = reply_items[1].split("~");
        String item_quantity_list[] = reply_items[0].split("~");
        String item_price_list[] = reply_items[2].split("~");
        if (item_quantity_list[0].equals("0")) {
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, 0, 0);
            item1_count.setModel(model1);
            item1_count.setEnabled(false);
        }else{
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, Integer.parseInt(item_quantity_list[0]), 1);
            item1_count.setModel(model1);
            item1_count.setEnabled(true);
        }
        if (item_quantity_list[1].equals("0")) {
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, 0, 0);
            item2_count.setModel(model1);
            item2_count.setEnabled(false);
        }else{
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, Integer.parseInt(item_quantity_list[1]), 1);
            item2_count.setModel(model1);
            item2_count.setEnabled(true);
        }
        item1.setText(item_list[1]);
        item2.setText(item_list[2]);
        item1_p.setText(item_price_list[1]);
        item2_p.setText(item_price_list[2]);
        Global.setVisible(false);
        JDialog ss = Global.shopping;
        ss.pack();
        ss.setLocationRelativeTo(null);
        ss.setVisible(true);

    }                                       

    private void sign_btnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String FiName = fn_sign.getText();
        String LaName = ln_sign.getText();
        String DOB= year.getText()+"-"+month.getText()+"-"+day.getText();
        String gender_1= "";
        if(male.isSelected())
        {
            gender_1 = "male";
        } else if (female.isSelected()){
            gender_1 = "female";
        }
        System.out.println(gender_1);
        String address_=address_sign.getText();
        String un=u_Name.getText();
        String pass1=pass_sign.getText();
        String cp1=cofirm_sign.getText();
        if (FiName.equals("") || LaName.equals("") || gender_1.equals("") || address_.equals("") || un.equals("") ||pass1.equals("")|| cp1.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the Fields !");
            

        } else if (!pass1.equals(cp1)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match!");
            pass_sign.setText("");
            cofirm_sign.setText("");
            
        } else {
                
                System.out.println("register" +"~"+un+ "~" + FiName + "~" +LaName + "~" + DOB + "~" +gender_1+ "~" + address_ + "~" + pass1+"~");
            try {
                // TODO add your handling code here:
                socket = new Socket("127.0.0.1", 7100); // localhost if this was on same machine or 127.0.0.1 // "172.20.10.4",
                System.out.println("CONNECTED TO Server");
                out = socket.getOutputStream();
                p = new PrintWriter(out, true);
                in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            } catch (IOException ex) {
                Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
            }

            String server_resp= "";
            try {
                System.out.println("Entered register!");
                //send the information to register function in server 
                p.println("register" +"~"+un+ "~" + FiName + "~" +LaName + "~" + DOB + "~" +gender_1+ "~" + address_ + "~" + pass1+"~");
                p.println("register" +"~"+un+ "~" + FiName + "~" +LaName + "~" + DOB + "~" +gender_1+ "~" + address_ + "~" + pass1+"~");
                server_resp = in.readLine();
                //socket.close();
            } catch (IOException e) {
                System.out.println(e);
            }
            if (server_resp.equals("successFinish!")) {
                utils_signup();
                JOptionPane.showMessageDialog(null, "You're now a member of the family !");
                register.setVisible(false);
            } else if (server_resp.equals("failFinish!")) {
                JOptionPane.showMessageDialog(null, "Username is already in use. Please Enter a New One.");
                p.println("Q");
            } else {
                JOptionPane.showMessageDialog(null, "Try Again Please!");
            }
        }
    }                                        

    private void shopping_login_signupActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        shopping.setVisible(false);
        Global.setVisible(true);
        
    }                                                     

    private void Back_signupActionPerformed(java.awt.event.ActionEvent evt) {                                            
        register.setVisible(false);
        utils_signup();
        Global.setVisible(true);
    }                                           

    private void BAck_loginActionPerformed(java.awt.event.ActionEvent evt) {                                           
        login.setVisible(false);
        utils_login();
        Global.setVisible(true);
    }                                          

    private void pcpageActionPerformed(java.awt.event.ActionEvent evt) {                                       
        cq_test.setText("computers");
        /*Get the list of available and unavailable items.
        1- send message to server as "ShowItems"
        2- server returns a message booleans in the order of items such that
        for item1 and item2 server will returns "1~0" meaning that item1
        is available while 2 is not. Can be fixed to nb of available if needed"
        */
        try {
            socket = new Socket("127.0.0.1",7100);
            out = socket.getOutputStream();
            p = new PrintWriter(out, true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            } catch (IOException ex) {
                Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
            }
            String server_answer = "";
            p.println("ShowItems~computers~q");
            try {
                server_answer=in.readLine();
            } catch (IOException ex) {
                Logger.getLogger(mainpagegui.class.getName()).log(Level.SEVERE, null, ex);
            }
        String reply_items[] = server_answer.split("~~~");
        String item_list[] = reply_items[1].split("~");
        String item_quantity_list[] = reply_items[0].split("~");
        String item_price_list[] = reply_items[2].split("~");
        if (item_quantity_list[0].equals("0")) {
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, 0, 0);
            item1_count.setModel(model1);
            item1_count.setEnabled(false);
        }else{
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, Integer.parseInt(item_quantity_list[0]), 1);
            item1_count.setModel(model1);
            item1_count.setEnabled(true);
        }
        if (item_quantity_list[1].equals("0")) {
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, 0, 0);
            item2_count.setModel(model1);
            item2_count.setEnabled(false);
        }else{
            SpinnerNumberModel model1 = new SpinnerNumberModel(0.0, 0.0, Integer.parseInt(item_quantity_list[1]), 1);
            item2_count.setModel(model1);
            item2_count.setEnabled(true);
        }
        item1_p.setText(item_price_list[1]);
        item2_p.setText(item_price_list[2]);
        item1.setText(item_list[1]);
        item2.setText(item_list[2]);
        Global.setVisible(false);
        JDialog ss = Global.shopping;
        ss.pack();
        ss.setLocationRelativeTo(null);
        ss.setVisible(true);

    }                                      

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {                                     
        DefaultListModel model = new DefaultListModel();
        int total=0;
        float total1=0;
        if(cart_s.c1q>0)
        {
            model.addElement(cart_s.c1 + "\t\t:"+(int)cart_s.c1q+" units\t\t" + cart_s.c1p*(int)cart_s.c1q + "$");
            total+=(int)cart_s.c1q;
            total1+=cart_s.c1p*(int)cart_s.c1q;
        }
        if(cart_s.e1q>0)
        {
            model.addElement(cart_s.e1 + "\t\t:"+(int)cart_s.e1q+" units\t\t"+ cart_s.e1p*(int)cart_s.e1q + "$");
            total+=(int)cart_s.e1q;
            total1+=cart_s.e1p*(int)cart_s.e1q;
        }
        if(cart_s.c2q>0)
        {
            model.addElement(cart_s.c2 + "\t\t:"+(int)cart_s.c2q+" units\t\t"+ cart_s.c2p*(int)cart_s.c2q + "$");
            total+=(int)cart_s.c2q;
            total1+=cart_s.c2p*(int)cart_s.c2q;
        }
        if(cart_s.e2q>0)
        {
            model.addElement(cart_s.e2 + "\t\t:"+(int)cart_s.e2q+" units\t\t"+ cart_s.e2p*(int)cart_s.e2q + "$");
            total+=(int)cart_s.e2q;
            total1+=cart_s.e2p*(int)cart_s.e2q;
        }
        String ttt= ""+total+" units";
        String ttt1= ""+total1+"$";
        total_price.setText(ttt1);
        total_cart.setText(ttt);
        cart_names.setModel(model);
        shopping.setVisible(false);
        JDialog ss = Global.cart_display;
        ss.pack();
        ss.setLocationRelativeTo(null);
        ss.setVisible(true);
    }                                    

    private void back_cartActionPerformed(java.awt.event.ActionEvent evt) {                                          
        cart_display.setVisible(false);
        Global.setVisible(true);
    }                                         
    
    private void utils_signup()
    {
        address_sign.setText("");
        cofirm_sign.setText("");
        fn_sign.setText("");
        ln_sign.setText("");
        pass_sign.setText("");
        u_Name.setText("");
        year.setText("");
        day.setText("");
        month.setText("");   
        male.setSelected(false);
        female.setSelected(false);
    }
    private void utils_login()
    {
        userName.setText("");
        password.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpagegui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpagegui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpagegui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpagegui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Global= new mainpagegui();
                Global.pack();
                Global.setLocationRelativeTo(null);
                Global.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton BAck_login;
    private javax.swing.JButton Back_signup;
    private javax.swing.JButton Buy;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField address_sign;
    private javax.swing.JButton back_cart;
    private javax.swing.JButton buypage;
    private javax.swing.JButton cart;
    private javax.swing.JDialog cart_display;
    private javax.swing.JList<String> cart_names;
    private javax.swing.JTextField cofirm_sign;
    private javax.swing.JLabel cq_test;
    private javax.swing.JTextField day;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fn_sign;
    private javax.swing.JLabel item1;
    private javax.swing.JSpinner item1_count;
    private javax.swing.JLabel item1_p;
    private javax.swing.JLabel item2;
    private javax.swing.JSpinner item2_count;
    private javax.swing.JLabel item2_p;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField ln_sign;
    private javax.swing.JDialog login;
    private javax.swing.JButton login_submit;
    private javax.swing.JButton loginbtn;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField month;
    private javax.swing.JTextField pass_sign;
    private javax.swing.JTextField password;
    private javax.swing.JButton pcpage;
    private javax.swing.JDialog register;
    private javax.swing.JDialog shopping;
    private javax.swing.JButton shopping_login_signup;
    private javax.swing.JButton sign_btn;
    private javax.swing.JButton signbtn;
    private javax.swing.JLabel total_cart;
    private javax.swing.JLabel total_price;
    private javax.swing.JTextField u_Name;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField year;
    // End of variables declaration                   
}
